version: '2'

services:

  # Network Pipeline Packet Processor
  # auto-publishes to the Django Rest Framework 
  # for making predictions on network traffic
  # using pre-trained deep neural networks
  # running in the AntiNex Core
  network-pipeline:
    container_name: "network-pipeline"
    hostname: network-pipeline
    image: jayjohnson/ai-core:latest
    network_mode: "host"
    env_file:
      - ./envs/pipeline-dev.env
    volumes:
      - /tmp:/tmp
    entrypoint: "/bin/sh -c 'cd /opt/antinex-pipeline && 
                 . ~/.venvs/venvdrfpipeline/bin/activate &&
                 /opt/antinex-pipeline/network_pipeline/scripts/packets_redis.py'"

