version: '2'

services:
  zap:
    container_name: "zap"
    image: owasp/zap2docker-live
    hostname: localhost
    ports:
      - 8090:8090
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    network_mode: "host"
